config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  get 'ping' => 'main#ping'
  resources :users
  resources :teams do
    resources :players do
      resources :box_scores
    end
  end

  namespace :api do
    namespace :v1 do
      get 'players/:id' => 'players#show'

      resources :authentication, only: [:create, :index]
      resources :teams, only: [:index, :create, :update, :show] do
        resources :games, only: [:create, :index, :update]
        resources :players, only: [:index, :show, :create, :update, :destroy]
      end
      resources :users, only: [:create]
      resources :box_scores, only: [:index]

      namespace :media do
        post 'upload_photo'
      end
    end
  end

end

app/models/box_score.rb
class BoxScore < ActiveRecord::Base
  belongs_to :game
  belongs_to :player

  def date
  	self.game.present? ? self.game.date : nil
  end

  def opponent
  	self.game.present? ? self.game.opponent : nil
  end
end

app/controllers/api/v1/box_scores_controller.rb
module Api
	module V1
		class BoxScoresController < BaseController
			def index
        render json: box_scores.to_json
			end

			private

			def box_scores
				scope = BoxScore.joins(:player, :game)
				scope = scope.select("players.number, players.name, TO_CHAR(games.date, 'MM/DD/YYYY'), games.opponent, box_scores.*")
				scope = scope.order("players.name")

				# Date format: &start_date='2016-11-01'
				scope = scope.where("games.date >= ?", params[:start_date]) if params[:start_date].present?

				# Date format: &end_date='2016-11-01'
				scope = scope.where("games.date <= ?", params[:end_date]) if params[:end_date].present?
				scope
			end
		end
	end
end

app/controllers/box_scores_controller.rb
class BoxScoresController < ApplicationController
	before_action :get_player
	before_action :validate_game, only: [:create, :update]
	before_action :find_or_create_game, only: [:create]

	def index
		@box_scores = @player.box_scores.joins(:game).order('games.date')
		@team = @player.team
	end

	def new
		@box_score = BoxScore.new(player_id: @player.id)
	end

	def create
		bs_params = box_score_params.merge({player_id: @player.id, game_id: @game.id})
		@box_score = BoxScore.new(bs_params)
		if @box_score.save
			redirect_to team_player_box_scores_path(@player.team, @player)
		else
			render :new and return
		end
	end

	def edit
		@box_score = BoxScore.find(params[:id])
	end

	def update
		@box_score = BoxScore.find(params[:id])
		if @box_score.update_attributes(box_score_params)
			update_game
			redirect_to team_player_box_scores_path(@player.team, @player)
		else
			render :new and return
		end
	end

	private

	def box_score_params
		params.require(:box_score).permit(:total_points, :assists,
			:rebounds, :two_point_make, :two_point_attempt, :three_point_make,
			:three_point_attempt, :one_point_make, :one_point_attempt)
	end

	def validate_game
		if params[:box_score_date].blank?
			flash.now[:alert] = 'Please specify a game date'
			@box_score = BoxScore.new(player_id: @player.id)
			render :new and return
		end

		if params[:box_score_opponent].blank?
			flash.now[:alert] = 'Please specify a game opponent'
			@box_score = BoxScore.new(player_id: @player.id)
			render :new and return
		end
	end

	def update_game
		game_date = Date.strptime(params['box_score_date'], '%m/%d/%Y')
		@game = @box_score.game
		@game.update_attributes(opponent: params[:box_score_opponent], date: game_date)
	end

	def find_or_create_game
		game_date = Date.strptime(params['box_score_date'], '%m/%d/%Y')
		@game = Game.where(opponent: params[:box_score_opponent], date: game_date).last
		if @game.blank?
			@game = Game.create(opponent: params[:box_score_opponent], date: game_date)
		end
	end

	def get_player
		@player = Player.find_by_id(params[:player_id])
		unless @player
			redirect_to root_path and return
		end
	end
end

app/helpers/box_scores_helper.rb
module BoxScoresHelper
end

app/views/box_scores/_form.html.erb
<div class="row" style="margin-top: 20px;">
  <%= form_for [team, player, box_score], html: {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= label_tag 'game', 'Game', class: "col-sm-2 control-label" %>
      <div class="col-sm-2">
        <%= text_field_tag 'box_score_date', display_date(box_score.date), placeholder: 'Date', class: "datepicker form-control" %>
      </div>
      <div class="col-sm-2">
        <%= text_field_tag 'box_score_opponent', box_score.opponent, placeholder: 'Opponent', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :total_points, class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :total_points, placeholder: 'Total', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :assists, class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :assists, placeholder: 'Assists', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :rebounds, class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :rebounds, placeholder: 'Reb.', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2"></div>
      <div class="col-sm-1">Makes</div>
      <div class="col-sm-1">Attempts</div>
    </div>
    <div class="form-group">
      <%= f.label :two_point_attempt, 'Two Point Field Goals', class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :two_point_make, placeholder: 'Makes', class: "form-control" %>
      </div>
      <div class="col-sm-1">
        <%= f.text_field :two_point_attempt, placeholder: 'Att.', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :three_point_attempt, 'Three Point Field Goals', class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :three_point_make, placeholder: 'Makes', class: "form-control" %>
      </div>
      <div class="col-sm-1">
        <%= f.text_field :three_point_attempt, placeholder: 'Att.', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :one_point_attempt, 'Free Throws', class: "col-sm-2 control-label" %>
      <div class="col-sm-1">
        <%= f.text_field :one_point_make, placeholder: 'Makes', class: "form-control" %>
      </div>
      <div class="col-sm-1">
        <%= f.text_field :one_point_attempt, placeholder: 'Att.', class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Save</button>
        <%= link_to 'Cancel', team_player_box_scores_path(team, player), class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({
      autoclose: true
    });
  });
</script>

app/views/box_scores/edit.html.erb
<h1><%= @player.name %>: <%= @box_score.opponent %> on <%= display_date(@box_score.date) %></h1>

<%= render partial: 'form', locals: {player: @player, team: @player.team, box_score: @box_score} %>

app/views/box_scores/index.html.erb
<div class="row" style="margin-top: 10px;">
  <h2><%= @player.name %> Box Scores</h2>
  <p class="pull-right"><%= link_to 'New', new_team_player_box_score_path(@team, @player), "class" => "btn btn-success" %></p>
</div>
<table class="table">
  <tr>
    <th>Date</th>
    <th>Opponent</th>
    <th>FG</th>
    <th>3PT</th>
    <th>FT</th>
    <th>PTS</th>
    <th></th>
  </tr>
  <% @box_scores.each do |box_score| %>
    <% game = box_score.game %>
    <tr>
      <td><%= display_date(game.date) %></td>
      <td><%= game.opponent %></td>
      <td><%= box_score.two_point_make %>/<%= box_score.two_point_attempt %></td>
      <td><%= box_score.three_point_make %>/<%= box_score.three_point_attempt %></td>
      <td><%= box_score.one_point_make %>/<%= box_score.one_point_attempt %></td>
      <td><%= box_score.total_points %></td>
      <td>
        <div class="pull-right">
          <%= link_to 'Edit', edit_team_player_box_score_path(@team, @player, box_score), "class" => "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  <tr></tr>
</table>

app/views/box_scores/new.html.erb
<h1>New Box Score</h1>

<%= render partial: 'form', locals: {player: @player, team: @player.team, box_score: @box_score} %>