config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  get 'ping' => 'main#ping'
  resources :users
  resources :teams do
    resources :players do
      resources :box_scores
    end
  end

  namespace :api do
    namespace :v1 do
      get 'players/:id' => 'players#show'

      resources :authentication, only: [:create, :index]
      resources :teams, only: [:index, :create, :update, :show] do
        resources :games, only: [:create, :index, :update]
        resources :players, only: [:index, :show, :create, :update, :destroy]
      end
      resources :users, only: [:create]
      resources :box_scores, only: [:index]

      namespace :media do
        post 'upload_photo'
      end
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_many :player_photos, dependent: :destroy

  has_many :box_scores
  has_many :games, through: :box_scores

  validates_uniqueness_of :number, scope: [:name, :team_id]

  def set_profile_photo(photo_id)
    # Unset all other player photos
    self.player_photos.each do |pp|
      pp.update_attributes(profile_photo: false)
    end

    photo = PlayerPhoto.find(photo_id)
    photo.profile_photo = true
    photo.player_id = self.id
    photo.save!
  end

  def profile_photo
    self.player_photos.where(profile_photo: true).first
  end
end

app/controllers/api/v1/players_controller.rb
module Api
  module V1
    class PlayersController < BaseController
      before_filter :find_team

      def index
        @players = @team.players
        render json: @players.to_json(include: :profile_photo)
      end

      def show
        @player = Player.find_by_id(params[:id])
        render json: @player.to_json(include: [:profile_photo, :team])
      end

      def create
        @player = @team.players.create(player_params)
        add_or_update_profile_photo
        render json: @player.to_json
      end

      def update
        @player = @team.players.find_by_id(params[:id])
        @player.update_attributes(player_params)
        add_or_update_profile_photo
        render json: @player.to_json
      end

      def destroy
        @player = @team.players.find_by_id(params[:id])
        @player.destroy
        render json: {}
      end

      private

      def add_or_update_profile_photo
        if params[:player][:profile_photo]
          @player.set_profile_photo(params[:player][:profile_photo][:id])
        end
      end

      def player_params
        params.require(:player).permit(:name, :number,
          :height_feet, :height_inches, :position, :school, :year,
          :gpa, :athletic_accomplishments, :colleges_interested)
      end

      def find_team
        @team = Team.find_by_id(params[:team_id])
      end
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :get_team

	def index
		@players = @team.players
	end

	def show
		@player = Player.find(params[:id])
	end

	def new
		@player = @team.players.build
	end

	def create
		@player = @team.players.build(player_params)
		if @player.save
			flash[:notice] = "Player has been created"
			redirect_to team_players_path(@team)
		else
			flash[:alert] = "There was an error #{@player.error_messages}"
			render :new
		end
	end

	def edit
		@player = Player.find(params[:id])
	end

	def update
		@player = Player.find(params[:id])
		if @player.update_attributes(player_params)
			flash[:notice] = "Player has been updated"
			redirect_to team_players_path(@team)
		else
			flash[:alert] = "There was an error #{@player.error_messages}"
			render :new
		end
	end

	private

	def player_params
		params.require(:player).permit(:number, :name)
	end

	def get_team
		@team = Team.find_by_id(params[:team_id])
		unless @team
			redirect_to root_path and return
		end
	end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="row" style="margin-top: 20px;">
  <%= form_for [@team, @player], html: {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= f.label :number, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :number %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Save</button>
        <%= link_to 'Cancel', team_players_path(@team), class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/players/edit.html.erb
<h1>Edit <%= @player.name %></h1>
<%= render 'form' %>

app/views/players/index.html.erb
<div class="row" style="margin-top: 10px;">
  <h2><%= @team.name %> Players</h2>
  <p class="pull-right"><%= link_to 'New', new_team_player_path(@team), "class" => "btn btn-success" %></p>
</div>
<table class="table">
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
  <% @players.each do |player| %>
    <tr>
      <td><%= player.number %></td>
      <td><%= player.name %></td>
      <td></td>
      <td>
        <div class="pull-right">
          <%= link_to 'Box Scores', team_player_box_scores_path(@team, player), "class" => "btn btn-primary" %>
          <%= link_to 'Edit', edit_team_player_path(@team, player), "class" => "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  <tr></tr>
</table>

app/views/players/new.html.erb
<h1>New Player</h1>
<%= render 'form' %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>