config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  get 'ping' => 'main#ping'
  resources :users
  resources :teams do
    resources :players do
      resources :box_scores
    end
  end

  namespace :api do
    namespace :v1 do
      get 'players/:id' => 'players#show'

      resources :authentication, only: [:create, :index]
      resources :teams, only: [:index, :create, :update, :show] do
        resources :games, only: [:create, :index, :update]
        resources :players, only: [:index, :show, :create, :update, :destroy]
      end
      resources :users, only: [:create]
      resources :box_scores, only: [:index]

      namespace :media do
        post 'upload_photo'
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Player Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Player Database', root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.name} (edit)", edit_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <div class="container" style="margin-top: 50px;">
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>